In [4]:
import pandas as pd
import numpy as np
import re

#Reading in Data
df = pd.read_csv('Dog_Names (1).csv')

#Sorting Values
df.sort_values('Count', ascending = False)

NameA = df
NameB = df
NameC = df
NameD = df
NameE = df
NameF = df
NameG = df
NameH = df
NameI = df
NameJ = df
NameK = df
NameL = df
NameM = df
NameN = df
NameO = df
NameP = df
NameQ = df
NameR = df
NameS = df
NameT = df
NameU = df
NameV = df
NameW = df
NameX = df
NameY = df
NameZ = df

#Creating array of letters to put into for loop
letters = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
Names = [NameA,NameB,NameC,NameD,NameE,NameF,NameG,NameH,NameI,NameJ,NameK,NameL,NameM,NameN,NameO,NameP,NameQ,NameR,
         NameS,NameT,NameU,NameV,NameW,NameX,NameY,NameZ]

#For loop that splits dogs names into seperate columns by letter
#It creates 26 new dataframes, one for each dog name starting with letters [a-z]
i=0
for x in letters:
   
    Names[i] = df.loc[df['DogName'].str.startswith(x)]
    #Renaming each column to specify the letter
    Names[i].columns = ['DogName-'+ x, 'Count-'+ x]
    #Resetting the index of each indvidual new dataframe
    Names[i] = Names[i].reset_index(drop=True)
    i=i+1

#Appending all the different dognames by letters into one dataframe
DogNames = pd.concat(Names,axis=1)

print(DogNames)

    DogName-A  Count-A  DogName-B  Count-B  DogName-C  Count-C   DogName-D  \
0        ABBY     47.0      BELLA    110.0    CHARLIE     60.0       DAISY
1       ANNIE     24.0      BUDDY     83.0     COOPER     54.0        DUKE
2      ATHENA     21.0     BAILEY     67.0      CHLOE     39.0      DENALI
3       ANGEL     17.0       BEAR     46.0       COCO     29.0      DIESEL
4       ASPEN     13.0     BANDIT     26.0     CHANCE     16.0      DAKOTA
5         ACE     12.0     BUSTER     24.0      CHEWY     16.0      DEXTER
6      APOLLO     12.0    BENTLEY     22.0     COPPER     13.0       DOZER
7      AURORA     12.0       BLUE     20.0       CODY     12.0       DIXIE
8      ARCHIE     10.0     BAXTER     17.0      CHICO     11.0      DALLAS
9       ALLIE      8.0         BO     15.0     CALLIE     10.0      DESHKA
10      ANGUS      8.0      BELLE     12.0     CASSIE     10.0     DIAMOND
11       ARLO      7.0        BOO     12.0      COCOA     10.0   DAISY MAE
12       AXEL      7.0     BOOMER     11.0      CHENA      9.0       DUSTY
13    ABIGAIL      6.0       BABY     10.0     COOKIE      9.0      DAWSON
14   ACHILLES      6.0       BEAU     10.0       CALI      8.0       DIEGO
15        ALI      6.0      BRUNO     10.0      COSMO      8.0        DASH
16      ATLAS      6.0     BRUTUS     10.0    CRICKET      8.0         DOC
17      ABBIE      5.0      BRODY      9.0      CHIEF      7.0       DUTCH
18      ADDIE      5.0      BUBBA      9.0    CHINOOK      7.0      DAPHNE
19       AJAX      5.0  BABY GIRL      7.0       CASH      6.0         DAX
20      ALICE      5.0      BANJO      7.0    CHARLEY      6.0     DELILAH
21      AMBER      5.0        BEN      7.0      CHEVY      6.0       DOBBY
22       ADAK      4.0     BERNIE      7.0      CHICA      6.0       DRAKE
23       ALEX      4.0      BRUCE      7.0       CHIP      6.0        DUDE
24    ALYESKA      4.0     BARLEY      6.0     CAESAR      5.0       DEUCE
25       ARES      4.0      BLAZE      6.0      CASEY      5.0       DINGO
26       ASHA      4.0      BOBBY      6.0       CHAI      5.0          DJ
27      ASHER      4.0       BOLT      6.0  CHARLOTTE      5.0       DOLLY
28      ASTRO      4.0      BOOTS      6.0      CHASE      5.0      DUDLEY
29     AUTUMN      4.0     BOWSER      6.0     CINDER      5.0  DAISY DUKE
..        ...      ...        ...      ...        ...      ...         ...
363       NaN      NaN        NaN      NaN        NaN      NaN         NaN
364       NaN      NaN        NaN      NaN        NaN      NaN         NaN
365       NaN      NaN        NaN      NaN        NaN      NaN         NaN
366       NaN      NaN        NaN      NaN        NaN      NaN         NaN
367       NaN      NaN        NaN      NaN        NaN      NaN         NaN
368       NaN      NaN        NaN      NaN        NaN      NaN         NaN
369       NaN      NaN        NaN      NaN        NaN      NaN         NaN
370       NaN      NaN        NaN      NaN        NaN      NaN         NaN
371       NaN      NaN        NaN      NaN        NaN      NaN         NaN
372       NaN      NaN        NaN      NaN        NaN      NaN         NaN
373       NaN      NaN        NaN      NaN        NaN      NaN         NaN
374       NaN      NaN        NaN      NaN        NaN      NaN         NaN
375       NaN      NaN        NaN      NaN        NaN      NaN         NaN
376       NaN      NaN        NaN      NaN        NaN      NaN         NaN
377       NaN      NaN        NaN      NaN        NaN      NaN         NaN
378       NaN      NaN        NaN      NaN        NaN      NaN         NaN
379       NaN      NaN        NaN      NaN        NaN      NaN         NaN
380       NaN      NaN        NaN      NaN        NaN      NaN         NaN
381       NaN      NaN        NaN      NaN        NaN      NaN         NaN
382       NaN      NaN        NaN      NaN        NaN      NaN         NaN
383       NaN      NaN        NaN      NaN        NaN      NaN         NaN
384       NaN      NaN        NaN      NaN        NaN      NaN         NaN
385       NaN      NaN        NaN      NaN        NaN      NaN         NaN
386       NaN      NaN        NaN      NaN        NaN      NaN         NaN
387       NaN      NaN        NaN      NaN        NaN      NaN         NaN
388       NaN      NaN        NaN      NaN        NaN      NaN         NaN
389       NaN      NaN        NaN      NaN        NaN      NaN         NaN
390       NaN      NaN        NaN      NaN        NaN      NaN         NaN
391       NaN      NaN        NaN      NaN        NaN      NaN         NaN
392       NaN      NaN        NaN      NaN        NaN      NaN         NaN

     Count-D   DogName-E  Count-E   ...       DogName-V  Count-V   DogName-W  \
0       64.0       ELLIE     21.0   ...          VIOLET      5.0      WILLOW
1       44.0        EMMA     17.0   ...           VADER      4.0     WINSTON
2       37.0        ELSA      7.0   ...         VANILLA      2.0      WATSON
3       22.0       EDDIE      6.0   ...       VALENTINO      1.0     WRIGLEY
4       19.0        ELLA      6.0   ...         VALERIE      1.0     WHISKEY
5       14.0       ELVIS      6.0   ...          VALLEY      1.0      WINNIE
6       14.0       EMBER      5.0   ...           VALOR      1.0       WALLY
7       13.0         EVA      5.0   ...             VAN      1.0     WHISPER
8       10.0      EASTON      4.0   ...          VAUGHN      1.0      WILLIE
9       10.0      EMMETT      4.0   ...     VELLA MARIE      1.0    WRANGELL
10       9.0        ENZO      4.0   ...           VELMA      1.0      WALTER
11       8.0        ECHO      3.0   ...            VENN      1.0       WILEY
12       8.0      EDISON      3.0   ...           VENNY      1.0      WILSON
13       7.0      EDWARD      3.0   ...      VENTA GUMS      1.0  WINCHESTER
14       7.0     ELEANOR      3.0   ...           VENTI      1.0      WICKET
15       6.0         ELI      3.0   ...           VENUS      1.0       WILLA
16       6.0        ESKA      3.0   ...           VERDE      1.0       WILLY
17       6.0    ESTRELLA      3.0   ...            VERN      1.0     WOODROW
18       5.0       EBONY      2.0   ...          VERONA      1.0        WREN
19       5.0       EEVEE      2.0   ...           VESPA      1.0       WYATT
20       5.0         EIN      2.0   ...          VESPER      1.0      WYNNIE
21       5.0    EINSTEIN      2.0   ...             VIA      1.0   WEDNESDAY
22       5.0   ELLIE MAY      2.0   ...        VICTORIA      1.0        WABB
23       5.0       ELSIE      2.0   ...       VIDA LOCA      1.0     WAFFLES
24       4.0       EMILY      2.0   ...          VIENNA      1.0       WALDO
25       4.0      EMMITT      2.0   ...            VIGO      1.0     WALDO V
26       4.0        ERIS      2.0   ...          VIKING      1.0       WALLE
27       4.0       ERNIE      2.0   ...         VINCENT      1.0      WALLEY
28       4.0         EVE      2.0   ...        VINCENZO      1.0      WALNUT
29       3.0  E.Z. RYDER      1.0   ...            VITO      1.0        WARD
..       ...         ...      ...   ...             ...      ...         ...
363      NaN         NaN      NaN   ...             NaN      NaN         NaN
364      NaN         NaN      NaN   ...             NaN      NaN         NaN
365      NaN         NaN      NaN   ...             NaN      NaN         NaN
366      NaN         NaN      NaN   ...             NaN      NaN         NaN
367      NaN         NaN      NaN   ...             NaN      NaN         NaN
368      NaN         NaN      NaN   ...             NaN      NaN         NaN
369      NaN         NaN      NaN   ...             NaN      NaN         NaN
370      NaN         NaN      NaN   ...             NaN      NaN         NaN
371      NaN         NaN      NaN   ...             NaN      NaN         NaN
372      NaN         NaN      NaN   ...             NaN      NaN         NaN
373      NaN         NaN      NaN   ...             NaN      NaN         NaN
374      NaN         NaN      NaN   ...             NaN      NaN         NaN
375      NaN         NaN      NaN   ...             NaN      NaN         NaN
376      NaN         NaN      NaN   ...             NaN      NaN         NaN
377      NaN         NaN      NaN   ...             NaN      NaN         NaN
378      NaN         NaN      NaN   ...             NaN      NaN         NaN
379      NaN         NaN      NaN   ...             NaN      NaN         NaN
380      NaN         NaN      NaN   ...             NaN      NaN         NaN
381      NaN         NaN      NaN   ...             NaN      NaN         NaN
382      NaN         NaN      NaN   ...             NaN      NaN         NaN
383      NaN         NaN      NaN   ...             NaN      NaN         NaN
384      NaN         NaN      NaN   ...             NaN      NaN         NaN
385      NaN         NaN      NaN   ...             NaN      NaN         NaN
386      NaN         NaN      NaN   ...             NaN      NaN         NaN
387      NaN         NaN      NaN   ...             NaN      NaN         NaN
388      NaN         NaN      NaN   ...             NaN      NaN         NaN
389      NaN         NaN      NaN   ...             NaN      NaN         NaN
390      NaN         NaN      NaN   ...             NaN      NaN         NaN
391      NaN         NaN      NaN   ...             NaN      NaN         NaN
392      NaN         NaN      NaN   ...             NaN      NaN         NaN

     Count-W DogName-X  Count-X DogName-Y  Count-Y DogName-Z  Count-Z
0       49.0      XENA      9.0     YUKON     25.0      ZOEY     25.0
1       18.0    XANDER      2.0      YUKI     10.0      ZEUS     22.0
2        8.0         X      1.0      YODA      5.0       ZOE     18.0
3        7.0    XAADAS      1.0      YETI      3.0     ZIGGY     10.0
4        6.0       XAN      1.0      YOGI      2.0      ZEKE      8.0
5        5.0    XANADY      1.0     YAGER      1.0      ZIVA      7.0
6        4.0    XERXES      1.0     YALLA      1.0     ZELDA      5.0
7        4.0      XINA      1.0      YARA      1.0     ZORRO      4.0
8        4.0       XUN      1.0    YARROW      1.0      ZACK      3.0
9        4.0      XYLA      1.0      YAYO      1.0      ZENA      3.0
10       3.0       NaN      NaN    YENTRA      1.0      ZERO      3.0
11       3.0       NaN      NaN    YIPPEE      1.0       ZAK      2.0
12       3.0       NaN      NaN      YKSI      1.0      ZARA      2.0
13       3.0       NaN      NaN      YOBO      1.0    ZEPHYR      2.0
14       2.0       NaN      NaN      YOLA      1.0  ZEPPELIN      2.0
15       2.0       NaN      NaN      YOLI      1.0      ZEVA      2.0
16       2.0       NaN      NaN     YONAH      1.0     ZIPPO      2.0
17       2.0       NaN      NaN      YUGI      1.0      ZORA      2.0
18       2.0       NaN      NaN   YUM YUM      1.0      ZOYA      2.0
19       2.0       NaN      NaN      YUMA      1.0      ZUZU      2.0
20       2.0       NaN      NaN      YUMI      1.0     ZADER      1.0
21       1.0       NaN      NaN     YUUKO      1.0     ZADIE      1.0
22       1.0       NaN      NaN      YZMA      1.0      ZAHA      1.0
23       1.0       NaN      NaN       NaN      NaN     ZAIRE      1.0
24       1.0       NaN      NaN       NaN      NaN     ZAMBI      1.0
25       1.0       NaN      NaN       NaN      NaN     ZAMBO      1.0
26       1.0       NaN      NaN       NaN      NaN    ZANDER      1.0
27       1.0       NaN      NaN       NaN      NaN      ZANE      1.0
28       1.0       NaN      NaN       NaN      NaN     ZAYCA      1.0
29       1.0       NaN      NaN       NaN      NaN     ZAZEE      1.0
..       ...       ...      ...       ...      ...       ...      ...
363      NaN       NaN      NaN       NaN      NaN       NaN      NaN
364      NaN       NaN      NaN       NaN      NaN       NaN      NaN
365      NaN       NaN      NaN       NaN      NaN       NaN      NaN
366      NaN       NaN      NaN       NaN      NaN       NaN      NaN
367      NaN       NaN      NaN       NaN      NaN       NaN      NaN
368      NaN       NaN      NaN       NaN      NaN       NaN      NaN
369      NaN       NaN      NaN       NaN      NaN       NaN      NaN
370      NaN       NaN      NaN       NaN      NaN       NaN      NaN
371      NaN       NaN      NaN       NaN      NaN       NaN      NaN
372      NaN       NaN      NaN       NaN      NaN       NaN      NaN
373      NaN       NaN      NaN       NaN      NaN       NaN      NaN
374      NaN       NaN      NaN       NaN      NaN       NaN      NaN
375      NaN       NaN      NaN       NaN      NaN       NaN      NaN
376      NaN       NaN      NaN       NaN      NaN       NaN      NaN
377      NaN       NaN      NaN       NaN      NaN       NaN      NaN
378      NaN       NaN      NaN       NaN      NaN       NaN      NaN
379      NaN       NaN      NaN       NaN      NaN       NaN      NaN
380      NaN       NaN      NaN       NaN      NaN       NaN      NaN
381      NaN       NaN      NaN       NaN      NaN       NaN      NaN
382      NaN       NaN      NaN       NaN      NaN       NaN      NaN
383      NaN       NaN      NaN       NaN      NaN       NaN      NaN
384      NaN       NaN      NaN       NaN      NaN       NaN      NaN
385      NaN       NaN      NaN       NaN      NaN       NaN      NaN
386      NaN       NaN      NaN       NaN      NaN       NaN      NaN
387      NaN       NaN      NaN       NaN      NaN       NaN      NaN
388      NaN       NaN      NaN       NaN      NaN       NaN      NaN
389      NaN       NaN      NaN       NaN      NaN       NaN      NaN
390      NaN       NaN      NaN       NaN      NaN       NaN      NaN
391      NaN       NaN      NaN       NaN      NaN       NaN      NaN
392      NaN       NaN      NaN       NaN      NaN       NaN      NaN

[393 rows x 52 columns]