In [2]:
import pandas as pd
import re

In [9]:
#Opening Text File and Reading it
text_file = open("marcRebillet.txt", "r")
lines = text_file.read()

#Splitting it into an array of one words, and making a list
Array = re.split(' |\n',lines)

#Creating a data frame and counting the unique values within it
df = pd.DataFrame({'Unique Marc Words':Array})
df['Frequency'] = df.groupby('Unique Marc Words')['Unique Marc Words'].transform('count')

#Dropping the duplicate values and only keepng one of them
df = df.drop_duplicates(subset=['Unique Marc Words', 'Frequency'])

#Locating the words with a frequency higher than 20
df.loc[(df['Frequency'] > 40)]

#Creating a new dataframe with only words said more than 40 times
#and ordering them from highest frequency to lowest frequency
df40 = df.loc[(df['Frequency'] > 40)]
df40.sort_values(['Frequency'], ascending = False)

#NEXT STEPS: 
#1. Change all capital letters to lowercase and then adjust accordingly
#Examples: the word 'oh' and 'Oh' are different, one has frequency = 71 and other frequency = 20.. need to add them
#2. Rearrange in order of highest frequency to lowest
#3.Maybe make an infographic or graph/chart and possibly only deal with frequency above a certain threshold

     Unique Marc Words  Frequency
77                 you        323
149                  I        302
7                  the        294
5                  and        247
34                   a        237
83                  to        224
104                 it        162
0              [Music]        158
96                 I'm        157
85                that        134
16                  on        117
132                 in         91
18                  of         90
224                 my         86
102               just         74
238               what         72
30                  oh         71
95                  so         70
79                it's         67
29                yeah         62
302                all         62
363             that's         62
76                  do         60
10               gonna         60
9                 baby         59
138             you're         59
1080               out         59
679               with         58
699                got         58
330               like         57
19                your         56
229                man         55
157               know         54
323                 is         54
468                for         53
90                this         53
279              about         51
7386             chill         50
154               well         50
141                 me         50
336                but         48
214                are         48
15                 get         48
1514             clean         46
113             really         45
166              right         45